FROM node:14.15.4
ENV NODE_ENV=production
WORKDIR /first-docker-app
COPY ["package*.json", "tsconfig.json", "/first-docker-app/"]
RUN npm install
COPY ./src ./src
RUN npx tsc
CMD [ "node", "dist/index.js" ]