version: '3.8'

services:
  express-server:
    image: node:14.15.4
    working_dir: /first-docker-app
    volumes:
      - ./:/first-docker-app
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run dev"
    container_name: express-server
    